@startuml
'https://plantuml.com/class-diagram

class Partida{}

class Interpol{
- Ladrones ladrones
- List<Ladron> posbilesLadrones
- Ladron ordenDeArresto

+ List<Ladron> buscarLadron()
+ Ladron emitirOrdenDeArresto()
}

class Ladrones{
- ArrayList<Ladron> ladrones
- inicializarLadrones()
- crearLadron()
+ getLadrones()
}

class Ladron{
- String nombre
- String genero
- String hobby
- String cabello
- String senia
- String vehiculo
}

Ladrones "1"*-down->"1...*" Ladron
Interpol -right-> Ladrones

Partida *-down->"1" Interpol
Partida *-down->"1" Ladrones

@enduml