@startuml

autonumber
title "Jugador visita banco de Montreal"
activate Jugador
Jugador -> "montreal: Ciudad": visitarEdificio(banco)
activate "montreal: Ciudad"
"montreal: Ciudad" -> "banco: Edificio": getPista()
activate "banco: Edificio"
"banco: Edificio" -> "banco: Edificio": mostrarPista()
"banco: Edificio" --> "montreal: Ciudad"
deactivate "banco: Edificio"
"montreal: Ciudad" --> Jugador
deactivate "montreal: Ciudad"

@enduml