@startuml

autonumber
title "Jugador visita 3 veces Aeropuerto y 55 veces Puerto"

activate Jugador
loop    i >= 3
    Jugador -> "montreal: Ciudad": visitarEdificio(aeropuerto)
    activate "montreal: Ciudad"
    "montreal: Ciudad" -> "aeropuerto: Edificio": getPista()
    activate "aeropuerto: Edificio"
    "aeropuerto: Edificio" -> "aeropuerto: Edificio": mostrarPista()
    "aeropuerto: Edificio" --> "montreal: Ciudad"
    deactivate "aeropuerto: Edificio"
    "montreal: Ciudad" --> Jugador
end loop
loop    i >= 55
    Jugador -> "montreal: Ciudad": visitarEdificio(puerto)
    "montreal: Ciudad" -> "puerto: Edificio": getPista()
    activate "puerto: Edificio"
    "puerto: Edificio" -> "puerto: Edificio": mostrarPista()
    "puerto: Edificio" --> "montreal: Ciudad"
    deactivate "puerto: Edificio"
    "montreal: Ciudad" --> Jugador
    deactivate "montreal: Ciudad"
    deactivate Jugador
end loop

@enduml