@startuml

autonumber
title jugadorViajaAMexico
activate Partida
Partida -> Jugador: setCiudadActual(mexico)
activate Jugador
Partida -> Jugador: calcularTiempoViaje(distancia)
Jugador --> Partida: tiempoViaje

deactivate Jugador
deactivate Partida

@enduml