@startuml

autonumber
title "Jugador visita banco de Montreal"
activate Jugador
Jugador -> "montreal: Ciudad": visitarEdificio(banco)
activate "montreal: Ciudad"
"montreal: Ciudad" -> "banco: Edificio": getPista(ciudadSig)
activate "banco: Edificio"
"banco: Edificio" -> "banco: Edificio": mostrarPista()

deactivate "montreal: Ciudad"
deactivate "banco: Edificio"

'Jugador tiene la ciudad actual como atributo

/'
ClaseJugador
visitarEdificio(Edificio edificio){
        ciudadActual.visitarEdificio(edificio);
}

ClaseCiudad
visitarEdificio(Ciudad ciudadSig, Edificio edificio){
    edificio.visitar(ciudadSig);
}

ClaseEdificio
visitar(Ciuadad ciudadSig){
    Reloj reloj = Reloj.getInstance();
    reloj.agregarHoras(obtenerCantidadHoras());
    mostrarPista(ciudadSig);
}

obtenerCantidadHoras(){if else, if else...}

mostrarPista(Ciudad ciudadSig){}

'/
@enduml