@startuml

autonumber
title "Detective sufre herida de cuchillo y duerme"
participant Jugador
participant "HeridoPorCuchillo: EstadoJugador"
participant "Dormido: EstadoDormido"
participant Reloj

activate Jugador
Jugador -> Jugador: serHeridoPorCuhillo()
create "HeridoPorCuchillo: EstadoJugador"
Jugador -> "HeridoPorCuchillo: EstadoJugador": pasarTiempo()
activate "HeridoPorCuchillo: EstadoJugador"
"HeridoPorCuchillo: EstadoJugador" -> Reloj:agregarHoras(HorasHerido)
activate Reloj
Reloj --> "HeridoPorCuchillo: EstadoJugador"
deactivate Reloj
"HeridoPorCuchillo: EstadoJugador" --> Jugador
deactivate "HeridoPorCuchillo: EstadoJugador"
Jugador -> Jugador: dormir()
create "Dormido: EstadoDormido"
Jugador -> "Dormido: EstadoDormido": pasarTiempo()
activate "Dormido: EstadoDormido"
"Dormido: EstadoDormido" -> Reloj: agregarHoras(HorasSuenio)
activate Reloj
Reloj --> "Dormido: EstadoDormido"
deactivate Reloj
"Dormido: EstadoDormido" --> Jugador
deactivate "Dormido: EstadoDormido"
deactivate Jugador

@enduml