@startuml

class Juego{
    - inicializarTiempo(hora:int, dia:int, mes:int, anio:int): Tiempo
}

class Tiempo{
    - calendario: GregorianCalendar

    + addHoras (horas: int): void
}

Juego -down-> Tiempo

@enduml