@startuml

class Juego{}

class Interpol{
- ladrones: Ladrones
- posbilesLadrones: List<Ladron>
- ordenDeArresto: Ladron

+ getPosiblesLadrones(): List<Ladron>
+ emitirOrdenDeArresto(): void
+ atraparSospechoso(): boolean
}

class Ladrones{
- ladrones: ArrayList<Ladron>
- inicializarLadrones(): void
- crearLadron(): void
+ getLadrones(): ArrayList<Ladron>
}

class Ladron{
- nombre: String
- genero: String
- hobby: String
- cabello: String
- senia: String
- vehiculo: String
}

Ladrones "1"-down->"1...*" Ladron
Interpol -right-> Ladrones

Juego *-down->"1" Interpol
Juego *-down->"1" Ladrones

@enduml