@startuml

abstract class Edificio{
    #comportamientoPistas: ComportamientoPistas
    #comportamientoDeDemora: ComportamientoDeDemora
    #comportamientoVisita: ComportamientoVisita
    --
    +{abstract}mostrarNombreDelEdificio(): void
    +mostrarPista(): void
    +entrarAlEdificio(): void
}

class EdificioAeropuerto {
    --
    +EdificioAeropuerto()
    +mostrarNombreDelEdificio()
}

class EdificioBanco {
    --
    +EdificioBanco()
    +mostrarNombreDelEdificio()
}

class EdificioBiblioteca {
    --
    +EdificioBiblioteca()
    +mostrarNombreDelEdificio()
}

class EdificioPuerto {
    --
    +EdificioPuerto()
    +mostrarNombreDelEdificio()
}

Edificio <|-down- EdificioAeropuerto
Edificio <|-down- EdificioBanco
Edificio <|-down- EdificioBiblioteca
Edificio <|-down- EdificioPuerto


@enduml