@startuml

class Ladron {
    -nombre: String
    -genero: String
    -hobby: String
    -cabello: String
    -senia: String
    -vehiculo: String
}

class Ladrones{
    - ladrones: ArrayList<Ladron>
    - inicializarLadrones(): void
    - crearLadron(): void
    + getLadrones(): ArrayList<Ladron>
}

Ladrones "1"-->"1...*" Ladron
@enduml