@startuml

class Partida {
    -jugador: Jugador
    -objetoRobado: ObjetoRobado
    -ciudades: ArrayList<Ciudad>
    --
    +Partida(nuevoJugador: Jugador, objetoRobado: ObjetoRobado, ciudades: ArrayList<Ciudad>)
    +buscarCiudad(nombreNuevaCiudad: String): Ciudad
}

@enduml