@startuml

class CalculadorTiempoViaje{
    -velocidad: int
    -latitudSalida: Double
    -longitudSalidad: Double
    -latitudDestino: Double
    -longitudDestino: Double
    --
    +CalculadorTiempoViaje(velocidad: int, latitudSalida: Double, longitudSalidad: Double, latitudDestino: Double, longitudDestino: Double)
    +obtenerDistancia(): Double
    +obtenerHorasDeViaje(): Int
}

@enduml