@startuml

class Ciudad {
    -nombre: String
    -bandera: String
    -moneda: String
    -geografia: String
    -hitos: String
    -industria: String
    -animales: String
    -personalidades: String
    -idioma: String
    -arte: String
    -religion: String
    -gobierno: String
    -varios: String
    -longitud: Double
    -latitud: Double
    -ciudadSiguiente: Ciudad
    -edificios: ArrayList<Edificio>
    -pasoLadron: boolean
    --
    +Ciudad(pistaCiudad: ArrayList<String>)
    +visitarEdicifio(unEdificio: Edificio): String
    +setCiudadSiguiente(ciudadSiguiente: Ciudad): void
    +setPistasEdificio(): void
    +viajarDesde(velocidad: int, ciudadSiguiente: Ciudad): void
    +viajarHasta(velocidad: int, latitud: Double, longitud: Double): void
}
@enduml