@startuml

class Juego{
    - inicializarJugador(nombre: String)
}

class Jugador {
    -nombre: String
    -ciudadActual: Ciudad
    -vecesHeridosPorCuchillo: int
    -tiempo: Tiempo


    +Jugador(nombre: String, ciudadInicial: Ciudad)
    +addArresto(): void
    +dormir(): int
    +serHeridoPorCuchillo(): int
    +serHeridoPorArmaDeFuego(): int
    +sanar(): void
    +viajar(ciudadSiguiente: Ciudad)
    +visitarEdificio(): void
}

interface Rango{}

interface EstadoJugador

Juego "1"*-right->"1" Jugador
Jugador "1"*-down->"1" Rango
Jugador "1"*-down->"1" EstadoJugador
@enduml